repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: "src/stories/__snapshots__/storyshots.spec.ts.snap"
        # exclude: tests/data
      - id: check-ast
      - id: check-yaml
        # exclude: services/config_gen/service_configs/data.neracoos.org_geoapi/pygeoapi.config.yaml
      - id: check-xml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files
        args: ["--maxkb=600"]
      - id: no-commit-to-branch

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.3.3" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
