repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: "src/stories/__snapshots__/storyshots.spec.ts.snap"
        # exclude: tests/data
      - id: check-ast
      - id: check-yaml
        # exclude: services/config_gen/service_configs/data.neracoos.org_geoapi/pygeoapi.config.yaml
      - id: check-xml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files
        args: ["--maxkb=600"]
        exclude: package-lock.json
      - id: no-commit-to-branch

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "0ee178619d696787ca73d210cc191d720868c631" # frozen: v3.9.6
    hooks:
      - id: prettier

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa # frozen: v1.29.0
    hooks:
      - id: zizmor
        files: "^\\.github"
        args: [--persona=pedantic]

  - repo: https://github.com/gulfofmaine/odp-releaser
    rev: edf009680fba6354fbf576bbbdc6d8dba1e50606 # frozen: main
    hooks:
      - id: validate-deploy-targets

update:
  cooldown_days: 7
