repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: "src/stories/__snapshots__/storyshots.spec.ts.snap"
        # exclude: tests/data
      - id: check-ast
      - id: check-yaml
        # exclude: services/config_gen/service_configs/data.neracoos.org_geoapi/pygeoapi.config.yaml
      - id: check-xml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files
        args: ["--maxkb=600"]
        exclude: package-lock.json
      - id: no-commit-to-branch

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "39e2973981e6d2f9b6c543b0086a2d2393abdc89" # frozen: v3.9.4
    hooks:
      - id: prettier

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: e3eebf65325ccc992422292cb7a4baee967cf815 # frozen: v1.26.1
    hooks:
      - id: zizmor
        files: "^\\.github"
        args: [--persona=pedantic]

update:
  cooldown_days: 7
