version: "3.7"

services:
  client:
    build:
      context: .
      target: develop
    image: gmri/neracoos-mariners-dashboard
    command: "yarn dev"
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_ERDDAP_SERVICE: https://buoybarn.neracoos.org
      # NEXT_PUBLIC_ERDDAP_SERVICE: http://localhost:8080
      NEXT_PUBLIC_PROXY_ROOT: https://proxy.neracoos.org/
      # NEXT_PUBLIC_PROXY_ROOT: http://localhost:9090/
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules/
  # test:
  #   build: .
  #   image: neracoos-react
  #   command: "yarn test --watchAll" # --coverage"
  #   environment:
  #     NEXT_PUBLIC_ERDDAP_SERVICE: http://localhost:8080/api/platforms/
  #   volumes:
  #   - .:/usr/src/app
  #   - /usr/src/app/node_modules/
