version: '2.4'

services:
  ionic:
    build: .
    image: neracoos-ionic
    ports:
    - "8100:8100"
    - "35729:35729"
    - "53703:53703"
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules/
  
  test:
    command: npm test
    build: .
    image: neracoos-ionic
    ports:
    - "9876:9876"
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules/
