services:
  client:
    build:
      context: .
      target: runner
    image: gmri/neracoos-mariners-dashboard
    # command: "npm run dev"
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_ERDDAP_SERVICE: https://buoybarn.neracoos.org
      # NEXT_PUBLIC_ERDDAP_SERVICE: http://localhost:8080
    # volumes:
    #   - .:/app:cached
    #   - /app/node_modules/
  # test:
  #   build: .
  #   image: neracoos-react
  #   command: "npm run test --watchAll" # --coverage"
  #   environment:
  #     NEXT_PUBLIC_ERDDAP_SERVICE: http://localhost:8080/api/platforms/
  #   volumes:
  #   - .:/usr/src/app
  #   - /usr/src/app/node_modules/
