version: "2.4"

services:
  client:
    build:
      context: .
      target: develop
      args:
        NEXT_PUBLIC_ERDDAP_SERVICE: https://buoybarn.neracoos.org
        NEXT_PUBLIC_PROXY_ROOT: https://proxy.neracoos.org/
    image: gmri/neracoos-mariners-dashboard
    command: "yarn dev"
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_ERDDAP_SERVICE: https://buoybarn.neracoos.org
      # REACT_APP_ERDDAP_SERVICE: http://localhost:8080
      NEXT_PUBLIC_PROXY_ROOT: https://proxy.neracoos.org/
      # REACT_APP_PROXY_ROOT: http://localhost:9090/
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./package.json:/usr/src/app/package.json:cached
      - ./yarn.lock:/usr/src/app/yarn.lock:cached
      - /usr/src/app/node_modules/
      - /usr/src/app/src/.next/
  # test:
  #   build: .
  #   image: neracoos-react
  #   command: "yarn test --watchAll" # --coverage"
  #   environment:
  #     REACT_APP_ERDDAP_SERVICE: http://localhost:8080/api/platforms/
  #   volumes:
  #   - .:/usr/src/app
  #   - /usr/src/app/node_modules/
