version: "2.4"

services:
  client:
    build: .
    image: neracoos-react
    command: "yarn start"
    ports:
      - "3000:3000"
    environment:
      REACT_APP_ERDDAP_SERVICE: http://localhost:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
