apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: gmri/neracoos-mariners-dashboard
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NEXT_PUBLIC_PROXY_ROOT: https://proxy.neracoos.org/
          NEXT_PUBLIC_ERDDAP_SERVICE: https://buoybarn.neracoos.org
deploy:
  kustomize:
    path: k8s/
