apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariners-dashboard
spec:
  selector:
    matchLabels:
      app: mariners-dashboard
  template:
    metadata:
      labels:
        app: mariners-dashboard
    spec:
      containers:
        - name: mariners-dashboard
          image: gmri/neracoos-mariners-dashboard
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
          ports:
            - containerPort: 3000
              name: http
