apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mariners-dashboard
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mariners-dashboard
                port:
                  number: 80
