apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mariners-dashboard
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: mariners-dashboard
              servicePort: 80
