import { PlatformFeature } from "Features/ERDDAP/types"

export const platforms: PlatformFeature[] = [
  {
    id: "BGXN3",
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-70.832867, 43.065303],
    },
    properties: {
      id: 144,
      readings: [
        {
          value: 0,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "northward_wind",
            short_name: undefined,
            long_name: "Wind Speed, Meridional",
            units: "m s-1",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wspv",
          constraints: {
            "station=": "BGXN3",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 12.8000001907349,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "dew_point_temperature",
            short_name: "DEWP",
            long_name: "Dewpoint Temperature",
            units: "celsius",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "dewp",
          constraints: {
            "station=": "BGXN3",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 2.59999990463257,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "wind_speed",
            short_name: "WSPD",
            long_name: "Wind Speed",
            units: "m/s",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wspd",
          constraints: {
            "station=": "BGXN3",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 270,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "wind_from_direction",
            short_name: "WD",
            long_name: "Wind Direction",
            units: "degrees",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wd",
          constraints: {
            "station=": "BGXN3",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 23.8999996185303,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "air_temperature",
            short_name: "AT",
            long_name: "Air Temperature",
            units: "celsius",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "atmp",
          constraints: {
            "station=": "BGXN3",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 2.59999990463257,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "eastward_wind",
            short_name: undefined,
            long_name: "Wind Speed, Zonal",
            units: "m s-1",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wspu",
          constraints: {
            "station=": "BGXN3",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
      ],
      attribution: [
        {
          program: {
            name: "NOAA National Estuarine Research Reserves",
            website: "https://coast.noaa.gov/nerrs",
          },
          attribution: "NOAA National Estuarine Research Reserves",
        },
      ],
      alerts: [],
      mooring_site_desc: "Great Bay Reserve, NH",
      active: true,
      ndbc_site_id: "BGXN3",
      uscg_light_letter: undefined,
      uscg_light_num: undefined,
      watch_circle_radius: undefined,
      programs: [9],
    },
  },
  {
    id: "NAXR1",
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-71.3394, 41.6389],
    },
    properties: {
      id: 87,
      readings: [
        {
          value: 310,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "wind_from_direction",
            short_name: "WD",
            long_name: "Wind Direction",
            units: "degrees",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wd",
          constraints: {
            "station=": "NAXR1",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 1007,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "air_pressure_at_sea_level",
            short_name: undefined,
            long_name: "Air Pressure",
            units: "hPa",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "bar",
          constraints: {
            "station=": "NAXR1",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 12.3000001907349,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "dew_point_temperature",
            short_name: "DEWP",
            long_name: "Dewpoint Temperature",
            units: "celsius",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "dewp",
          constraints: {
            "station=": "NAXR1",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 2,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "eastward_wind",
            short_name: undefined,
            long_name: "Wind Speed, Zonal",
            units: "m s-1",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wspu",
          constraints: {
            "station=": "NAXR1",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: -1.70000004768372,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "northward_wind",
            short_name: undefined,
            long_name: "Wind Speed, Meridional",
            units: "m s-1",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wspv",
          constraints: {
            "station=": "NAXR1",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 2.59999990463257,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "wind_speed",
            short_name: "WSPD",
            long_name: "Wind Speed",
            units: "m/s",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wspd",
          constraints: {
            "station=": "NAXR1",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 26.2999992370605,
          time: "2020-09-23T20:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "air_temperature",
            short_name: "AT",
            long_name: "Air Temperature",
            units: "celsius",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "atmp",
          constraints: {
            "station=": "NAXR1",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: -4,
          time: "2020-09-22T16:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "tendency_of_air_pressure",
            short_name: undefined,
            long_name: "Pressure Tendency",
            units: "hPa",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "ptdy",
          constraints: {
            "station=": "NAXR1",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
      ],
      attribution: [
        {
          program: {
            name: "NOAA National Estuarine Research Reserves",
            website: "https://coast.noaa.gov/nerrs",
          },
          attribution: "NOAA National Estuarine Research Reserves",
        },
      ],
      alerts: [],
      mooring_site_desc: "Naragansett Bay Reserve, RI",
      active: true,
      ndbc_site_id: "NAXR1",
      uscg_light_letter: undefined,
      uscg_light_num: undefined,
      watch_circle_radius: undefined,
      programs: [9],
    },
  },
  {
    id: "WAXM3",
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-70.5251, 41.5817],
    },
    properties: {
      id: 138,
      readings: [
        {
          value: 1007,
          time: "2020-09-23T19:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "air_pressure_at_sea_level",
            short_name: undefined,
            long_name: "Air Pressure",
            units: "hPa",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "bar",
          constraints: {
            "station=": "WAXM3",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 14.1000003814697,
          time: "2020-09-23T19:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "dew_point_temperature",
            short_name: "DEWP",
            long_name: "Dewpoint Temperature",
            units: "celsius",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "dewp",
          constraints: {
            "station=": "WAXM3",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 1.5,
          time: "2020-09-23T19:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "wind_speed",
            short_name: "WSPD",
            long_name: "Wind Speed",
            units: "m/s",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wspd",
          constraints: {
            "station=": "WAXM3",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 21,
          time: "2020-09-23T19:45:00Z",
          depth: undefined,
          data_type: {
            standard_name: "air_temperature",
            short_name: "AT",
            long_name: "Air Temperature",
            units: "celsius",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "atmp",
          constraints: {
            "station=": "WAXM3",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: -4,
          time: "2020-09-22T17:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "tendency_of_air_pressure",
            short_name: undefined,
            long_name: "Pressure Tendency",
            units: "hPa",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "ptdy",
          constraints: {
            "station=": "WAXM3",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
      ],
      attribution: [
        {
          program: {
            name: "NOAA National Estuarine Research Reserves",
            website: "https://coast.noaa.gov/nerrs",
          },
          attribution: "NOAA National Estuarine Research Reserves",
        },
      ],
      alerts: [],
      mooring_site_desc: "Waquoit Bay Reserve, MA",
      active: true,
      ndbc_site_id: "WAXM3",
      uscg_light_letter: undefined,
      uscg_light_num: undefined,
      watch_circle_radius: undefined,
      programs: [9],
    },
  },
  {
    id: "44098",
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-70.169, 42.801],
    },
    properties: {
      id: 112,
      readings: [
        {
          value: 7.90000009536743,
          time: "2020-09-23T21:05:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_swell_wave_period",
            short_name: undefined,
            long_name: "Wave Period, Average",
            units: "s",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "apd",
          constraints: {
            "apd>=": -0.1,
            "station=": "44098",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 95,
          time: "2020-09-23T21:05:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_wave_to_direction",
            short_name: undefined,
            long_name: "Wave Direction",
            units: "degrees_true",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "mwd",
          constraints: {
            "station=": "44098",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 15.3999996185303,
          time: "2020-09-23T21:05:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_temperature",
            short_name: undefined,
            long_name: "SST",
            units: "degree_C",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wtmp",
          constraints: {
            "wtmp>": 0,
            "station=": "44098",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 13,
          time: "2020-09-23T21:05:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_swell_wave_period",
            short_name: undefined,
            long_name: "Wave Period, Dominant",
            units: "s",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "dpd",
          constraints: {
            "dpd>=": -0.1,
            "station=": "44098",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 1.39999997615814,
          time: "2020-09-23T21:05:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_wave_significant_height",
            short_name: undefined,
            long_name: "Wave Height",
            units: "m",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wvht",
          constraints: {
            "station=": "44098",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
      ],
      attribution: [
        {
          program: {
            name: "University of New Hampshire",
            website: "https://www.unh.edu/eos/ocean-process-analysis-laboratory",
          },
          attribution: "University of New Hampshire",
        },
      ],
      alerts: [],
      mooring_site_desc: "Jeffreys Ledge Waverider Buoy",
      active: true,
      ndbc_site_id: "44098",
      uscg_light_letter: undefined,
      uscg_light_num: undefined,
      watch_circle_radius: undefined,
      programs: [5],
    },
  },
  {
    id: "44013",
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-70.69, 42.35],
    },
    properties: {
      id: 108,
      readings: [
        {
          value: 1.20000004768372,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_wave_significant_height",
            short_name: undefined,
            long_name: "Wave Height",
            units: "m",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wvht",
          constraints: {
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 310,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "wind_from_direction",
            short_name: "WD",
            long_name: "Wind Direction",
            units: "degrees",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wd",
          constraints: {
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 4,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "wind_speed",
            short_name: "WSPD",
            long_name: "Wind Speed",
            units: "m/s",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wspd",
          constraints: {
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 13.6000003814697,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "dew_point_temperature",
            short_name: "DEWP",
            long_name: "Dewpoint Temperature",
            units: "celsius",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "dewp",
          constraints: {
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 0.600000023841858,
          time: "2020-09-23T12:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "tendency_of_air_pressure",
            short_name: undefined,
            long_name: "Pressure Tendency",
            units: "hPa",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "ptdy",
          constraints: {
            "ptdy>": 0,
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 5,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "wind_speed_of_gust",
            short_name: "WGST",
            long_name: "Wind Gust",
            units: "m/s",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "gst",
          constraints: {
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 3.09999990463257,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "eastward_wind",
            short_name: undefined,
            long_name: "Wind Speed, Zonal",
            units: "m s-1",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wspu",
          constraints: {
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 7.19999980926514,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_swell_wave_period",
            short_name: undefined,
            long_name: "Wave Period, Average",
            units: "s",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "apd",
          constraints: {
            "apd>": 0,
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: -2.59999990463257,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "northward_wind",
            short_name: undefined,
            long_name: "Wind Speed, Meridional",
            units: "m s-1",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wspv",
          constraints: {
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 13,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_swell_wave_period",
            short_name: undefined,
            long_name: "Wave Period, Dominant",
            units: "s",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "dpd",
          constraints: {
            "dpd>": 0,
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 103,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_wave_to_direction",
            short_name: undefined,
            long_name: "Wave Direction",
            units: "degrees_true",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "mwd",
          constraints: {
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 1004.5,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "air_pressure_at_sea_level",
            short_name: undefined,
            long_name: "Air Pressure",
            units: "hPa",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "bar",
          constraints: {
            "bar>": 0,
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 19.8999996185303,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "air_temperature",
            short_name: "AT",
            long_name: "Air Temperature",
            units: "celsius",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "atmp",
          constraints: {
            "atmp>": 0,
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 16.3999996185303,
          time: "2020-09-23T20:50:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_temperature",
            short_name: undefined,
            long_name: "SST",
            units: "degree_C",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wtmp",
          constraints: {
            "wtmp>": 0,
            "station=": "44013",
          },
          dataset: "cwwcNDBCMet",
          start_time: "1970-02-26T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
      ],
      attribution: [
        {
          program: {
            name: "NOAA NDBC",
            website: "https://www.ndbc.noaa.gov",
          },
          attribution: "NOAA National Buoy Data Center",
        },
      ],
      alerts: [],
      mooring_site_desc: "Boston Harbor",
      active: true,
      ndbc_site_id: "44013",
      uscg_light_letter: undefined,
      uscg_light_num: undefined,
      watch_circle_radius: undefined,
      programs: [3],
    },
  },
  {
    id: "E01 - 44032",
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-69.3578, 43.7148],
    },
    properties: {
      id: 103,
      readings: [
        {
          value: 17.8299999237061,
          time: "2020-09-23T21:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "air_temperature",
            short_name: "AT",
            long_name: "Air Temperature",
            units: "celsius",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "air_temperature",
          constraints: {
            "air_temperature_qc=": 0,
          },
          dataset: "E01_met_all",
          start_time: "2001-07-09T12:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 2999.3720703125,
          time: "2020-09-23T21:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "visibility_in_air",
            short_name: "VIS",
            long_name: "Visibility",
            units: "meters",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "visibility",
          constraints: {
            "visibility_qc=": 0,
          },
          dataset: "E01_met_all",
          start_time: "2001-07-09T12:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 7.09499979019165,
          time: "2020-09-23T21:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "wind_speed_of_gust",
            short_name: "WGST",
            long_name: "Wind Gust",
            units: "m/s",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "wind_gust",
          constraints: {},
          dataset: "E01_met_all",
          start_time: "2001-07-09T12:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 6.11100006103516,
          time: "2020-09-23T21:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "wind_speed",
            short_name: "WSPD",
            long_name: "Wind Speed",
            units: "m/s",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "wind_speed",
          constraints: {},
          dataset: "E01_met_all",
          start_time: "2001-07-09T12:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 32.4083671569824,
          time: "2020-09-23T21:00:00Z",
          depth: 20,
          data_type: {
            standard_name: "sea_water_salinity",
            short_name: "S",
            long_name: "Salinity",
            units: "psu",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "salinity",
          constraints: {
            "depth=": 20,
            "conductivity_qc=": 0,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 32.5865707397461,
          time: "2020-09-23T21:00:00Z",
          depth: 50,
          data_type: {
            standard_name: "sea_water_salinity",
            short_name: "S",
            long_name: "Salinity",
            units: "psu",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "salinity",
          constraints: {
            "depth=": 50,
            "salinity_qc=": 0,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 32.4281005859375,
          time: "2020-09-23T21:00:00Z",
          depth: 1,
          data_type: {
            standard_name: "sea_water_salinity",
            short_name: "S",
            long_name: "Salinity",
            units: "psu",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "salinity",
          constraints: {
            "depth=": 1,
            "salinity_qc=": 0,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 0.990400016307831,
          time: "2020-09-23T21:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "significant_wave_height",
            short_name: "SWH",
            long_name: "Significant Wave Height",
            units: "m",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "significant_wave_height_3",
          constraints: {
            "significant_wave_height_3_qc=": 0,
          },
          dataset: "E01_waves_mstrain_all",
          start_time: "2019-05-29T19:13:14Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 1.58270001411438,
          time: "2020-09-23T21:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "max_wave_height",
            short_name: "MWH",
            long_name: "Maximum Wave Height",
            units: "m",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "maximum_wave_height_3",
          constraints: {
            "maximum_wave_height_3_qc=": 0,
          },
          dataset: "E01_waves_mstrain_all",
          start_time: "2019-05-29T19:13:50Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 281.700012207031,
          time: "2020-09-23T21:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "wind_from_direction",
            short_name: "WD",
            long_name: "Wind Direction",
            units: "degrees",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "wind_direction",
          constraints: {},
          dataset: "E01_met_all",
          start_time: "2001-07-09T12:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 19.9444007873535,
          time: "2019-12-30T17:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_water_velocity",
            short_name: "CSPD",
            long_name: "Current Speed",
            units: "cm/s",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "current_speed",
          constraints: {
            "sea_water_velocity_qc=": 0,
          },
          dataset: "E01_aanderaa_all",
          start_time: "2001-07-09T12:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 38.6580009460449,
          time: "2020-09-23T21:00:00Z",
          depth: 1,
          data_type: {
            standard_name: "sea_water_electrical_conductivity",
            short_name: "COND",
            long_name: "Conductivity",
            units: "siemens/m",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "conductivity",
          constraints: {
            "depth=": 1,
            "conductivity_qc=": 0,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 266.383209228516,
          time: "2019-12-30T17:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "direction_of_sea_water_velocity",
            short_name: "CDIR",
            long_name: "Current Direction",
            units: "angular_degrees",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "current_direction",
          constraints: {
            "direction_of_sea_water_velocity_qc=": 0,
          },
          dataset: "E01_aanderaa_all",
          start_time: "2001-07-09T12:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 4,
          time: "2020-09-23T21:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "period",
            short_name: "DWP",
            long_name: "Dominant Wave Period",
            units: "s",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "dominant_wave_period",
          constraints: {
            "dominant_wave_period_qc=": 0,
          },
          dataset: "E01_accelerometer_all",
          start_time: "2002-01-08T20:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 1003.24731445312,
          time: "2020-09-23T21:00:00Z",
          depth: undefined,
          data_type: {
            standard_name: "barometric_pressure",
            short_name: "BP",
            long_name: "Barometric Pressure",
            units: "millibars",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "barometric_pressure",
          constraints: {
            "barometric_pressure_qc=": 0,
          },
          dataset: "E01_met_all",
          start_time: "2001-07-09T12:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 24.9406394958496,
          time: "2020-09-23T21:00:00Z",
          depth: 50,
          data_type: {
            standard_name: "sea_water_density",
            short_name: "SIGMAT",
            long_name: "Sigma-T",
            units: "kg/m^3",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "sigma_t",
          constraints: {
            "depth=": 50,
            "sigma_t_qc=": 0,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 36.4113998413086,
          time: "2020-09-23T21:00:00Z",
          depth: 50,
          data_type: {
            standard_name: "sea_water_electrical_conductivity",
            short_name: "COND",
            long_name: "Conductivity",
            units: "siemens/m",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "conductivity",
          constraints: {
            "depth=": 50,
            "conductivity_qc=": 0,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 24.3133850097656,
          time: "2020-09-23T21:00:00Z",
          depth: 1,
          data_type: {
            standard_name: "sea_water_density",
            short_name: "SIGMAT",
            long_name: "Sigma-T",
            units: "kg/m^3",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "sigma_t",
          constraints: {
            "depth=": 1,
            "sigma_t_qc=": 0,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 38.0896987915039,
          time: "2020-09-23T21:00:00Z",
          depth: 20,
          data_type: {
            standard_name: "sea_water_electrical_conductivity",
            short_name: "COND",
            long_name: "Conductivity",
            units: "siemens/m",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "conductivity",
          constraints: {
            "depth=": 20,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 13.4460000991821,
          time: "2020-09-23T21:00:00Z",
          depth: 1,
          data_type: {
            standard_name: "sea_water_temperature",
            short_name: "WT",
            long_name: "Water Temperature",
            units: "celsius",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "temperature",
          constraints: {
            "depth=": 1,
            "temperature_qc=": 0,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 12.8339996337891,
          time: "2020-09-23T21:00:00Z",
          depth: 20,
          data_type: {
            standard_name: "sea_water_temperature",
            short_name: "WT",
            long_name: "Water Temperature",
            units: "celsius",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "temperature",
          constraints: {
            "depth=": 20,
            "temperature_qc=": 0,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 24.4188423156738,
          time: "2020-09-23T21:00:00Z",
          depth: 20,
          data_type: {
            standard_name: "sea_water_density",
            short_name: "SIGMAT",
            long_name: "Sigma-T",
            units: "kg/m^3",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "sigma_t",
          constraints: {
            "depth=": 20,
            "sigma_t_qc=": 0,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 10.7512998580933,
          time: "2020-09-23T21:00:00Z",
          depth: 50,
          data_type: {
            standard_name: "sea_water_temperature",
            short_name: "WT",
            long_name: "Water Temperature",
            units: "celsius",
          },
          server: "http://www.neracoos.org/erddap",
          variable: "temperature",
          constraints: {
            "depth=": 50,
            "temperature_qc=": 0,
          },
          dataset: "E01_sbe37_all",
          start_time: "2018-09-29T02:00:00Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
      ],
      attribution: [
        {
          program: {
            name: "University of Maine",
            website: "http://gyre.umeoce.maine.edu/gomoos.php",
          },
          attribution: "University of Maine",
        },
      ],
      alerts: [],
      mooring_site_desc: "Central Maine Shelf",
      active: true,
      ndbc_site_id: "44032",
      uscg_light_letter: "E",
      uscg_light_num: "30 (4935)",
      watch_circle_radius: undefined,
      programs: [1],
    },
  },
  {
    id: "44005",
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-69.22, 43.17],
    },
    properties: {
      id: 139,
      readings: [],
      attribution: [
        {
          program: {
            name: "NOAA NDBC",
            website: "https://www.ndbc.noaa.gov",
          },
          attribution: "NOAA National Data Buoy Center",
        },
      ],
      alerts: [
        {
          start_time: "2020-02-19",
          end_time: undefined,
          message:
            'The buoy was retrieved on 12/29/19. Data will be restored during our next service visit to this location. When a date is known it will be posted in the <a href="http://www.ndbc.noaa.gov/ops.shtml" target="_blank">Maintenance Schedule.</a>',
          level: "INFO",
        },
      ],
      mooring_site_desc: "Cashes Ledge",
      active: true,
      ndbc_site_id: "44005",
      uscg_light_letter: undefined,
      uscg_light_num: undefined,
      watch_circle_radius: undefined,
      programs: [3],
    },
  },
  {
    id: "CDIP154",
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-71.1217, 40.981],
    },
    properties: {
      id: 90,
      readings: [
        {
          value: 17.5,
          time: "2020-09-23T20:26:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_water_temperature",
            short_name: "WT",
            long_name: "Water Temperature",
            units: "celsius",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wtmp",
          constraints: {
            "wtmp>": 0,
            "station=": "44097",
          },
          dataset: "cwwcNDBCMet",
          start_time: "2019-05-23T17:14:27Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 5.09999990463257,
          time: "2020-09-23T20:26:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_swell_wave_period",
            short_name: undefined,
            long_name: "Wave Period, Average",
            units: "s",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "apd",
          constraints: {
            "apd>": 0,
            "station=": "44097",
          },
          dataset: "cwwcNDBCMet",
          start_time: "2019-08-21T17:56:25Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 120,
          time: "2020-09-23T20:26:00Z",
          depth: undefined,
          data_type: {
            standard_name: "mean_wave_direction",
            short_name: "MWD",
            long_name: "Mean Wave Direction",
            units: "degrees",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "mwd",
          constraints: {
            "mwd>": 0,
            "station=": "44097",
          },
          dataset: "cwwcNDBCMet",
          start_time: "2019-05-23T17:15:40Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 13,
          time: "2020-09-23T20:26:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_swell_wave_period",
            short_name: undefined,
            long_name: "Wave Period, Dominant",
            units: "s",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "dpd",
          constraints: {
            "dpd>": 0,
            "station=": "44097",
          },
          dataset: "cwwcNDBCMet",
          start_time: "2019-05-23T17:15:24Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
        {
          value: 1.39999997615814,
          time: "2020-09-23T20:26:00Z",
          depth: undefined,
          data_type: {
            standard_name: "sea_surface_wave_significant_height",
            short_name: undefined,
            long_name: "Wave Height",
            units: "m",
          },
          server: "https://coastwatch.pfeg.noaa.gov/erddap",
          variable: "wvht",
          constraints: {
            "wvht>": 0,
            "station=": "44097",
          },
          dataset: "cwwcNDBCMet",
          start_time: "2019-05-23T17:14:56Z",
          flood_levels: [],
          datum_offsets: {},
          highlighted: "No",
          extrema: false,
          type: "Observation",
        },
      ],
      attribution: [
        {
          program: {
            name: "CDIP - Coastal Data Information Program",
            website: "http://cdip.ucsd.edu/",
          },
          attribution: "USACE/CDIP Wave Buoy",
        },
      ],
      alerts: [],
      mooring_site_desc: "Block Island, RI",
      active: true,
      ndbc_site_id: "44097",
      uscg_light_letter: undefined,
      uscg_light_num: undefined,
      watch_circle_radius: undefined,
      programs: [10],
    },
  },
]
