name: Continuous Integration

on: [push]

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Login to Docker Hub"
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest Docker image
        run: docker pull gmri/neracoos-mariners-dashboard:latest
        continue-on-error: true

      - name: Build Docker image
        run: docker-compose build client

      - name: Tag Docker image
        run: docker tag gmri/neracoos-mariners-dashboard:latest gmri/neracoos-mariners-dashboard:${{ github.sha }}

      - name: Push Docker image
        run: docker push gmri/neracoos-mariners-dashboard:${{ github.sha }}

  unit_tests:
    name: Unit tests and coverage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Login to Docker Hub"
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull gmri/neracoos-mariners-dashboard:${{ github.sha }}

      - name: Tag Docker image
        run: docker tag gmri/neracoos-mariners-dashboard:${{ github.sha }} gmri/neracoos-mariners-dashboard:latest

      - name: Run unit tests and coverage
        run: docker-compose run -e CI=true client yarn test-with-codacy-coverage
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  cypress:
    name: Cypress integration tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Login to Docker Hub"
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull gmri/neracoos-mariners-dashboard:${{ github.sha }}

      - name: Tag Docker image
        run: docker tag gmri/neracoos-mariners-dashboard:${{ github.sha }} gmri/neracoos-mariners-dashboard:latest

      - name: Install Cypress and wait on
        run: npm install -g cypress@3.1.2 wait-on

      - name: Start container
        run: docker-compose up -d client

      - name: Wait for container to become avaliable
        run: npx  wait-on http://localhost:300

      - name: Run Cypress
        run: cypress run
