name: CI

on: [push]

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: "Unit tests"
        run: docker-compose run -e CI=true client yarn test
